//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int adress_id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string town { get; set; }
        public int customer_no { get; set; }
        public string address_text { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
