//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public int AdminLogin_id { get; set; }
        public string admin_email { get; set; }
        public string admin_password { get; set; }
        public string admin_repassword { get; set; }
    }
}
