//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourites
    {
        public long favourite_id { get; set; }
        public int customer_no { get; set; }
        public int product_no { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
