//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int FooterId { get; set; }
        public string descript_txt { get; set; }
        public string location_txt { get; set; }
        public string location_head { get; set; }
        public string account_txt { get; set; }
        public string account_head { get; set; }
        public string main_txt { get; set; }
        public string main_head { get; set; }
        public string footer_menu_txt { get; set; }
        public string menu_head { get; set; }
        public string account_txt_1 { get; set; }
        public string main_txt_1 { get; set; }
        public string main_txt_3 { get; set; }
        public string footer_menu_txt_1 { get; set; }
    }
}
