//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderT
    {
        public int order_id { get; set; }
        public int customer_no { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal price { get; set; }
        public int order_num { get; set; }
        public Nullable<int> product_no { get; set; }
        public Nullable<int> product_number { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
