//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideLogo
    {
        public int SlideLogoId { get; set; }
        public string SlideImage { get; set; }
        public string Logo { get; set; }
        public string SlideImage_1 { get; set; }
        public string SlideImage_2 { get; set; }
    }
}
