//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Aslan_Commerce_vtEntities : DbContext
    {
        public Aslan_Commerce_vtEntities()
            : base("name=Aslan_Commerce_vtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<OrderT> OrderT { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Command> Product_Command { get; set; }
        public virtual DbSet<Sub_Category> Sub_Category { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AdminLogin> AdminLogin { get; set; }
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<Footer> Footer { get; set; }
        public virtual DbSet<Nav> Nav { get; set; }
        public virtual DbSet<SlideLogo> SlideLogo { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<WebFooter> WebFooter { get; set; }
    }
}
