//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vegan_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebFooter
    {
        public int WebId { get; set; }
        public string contact_txt { get; set; }
        public string support_txt { get; set; }
        public string contact_head { get; set; }
        public string support_head { get; set; }
        public string support_txt_1 { get; set; }
    }
}
